package Pojo;
// Generated 09.May.2019 23:00:31 by Hibernate Tools 4.3.1


/**
 * Musteri generated by hbm2java
 */
public class Musteri  implements java.io.Serializable {


     private int musteriId;
     private String ad;
     private String soyad;
     private long telno;
     private String cinsiyet;
     private long tc;

    public Musteri() {
    }

    public Musteri(int musteriId, String ad, String soyad, long telno, String cinsiyet, long tc) {
       this.musteriId = musteriId;
       this.ad = ad;
       this.soyad = soyad;
       this.telno = telno;
       this.cinsiyet = cinsiyet;
       this.tc = tc;
    }
   
    public int getMusteriId() {
        return this.musteriId;
    }
    
    public void setMusteriId(int musteriId) {
        this.musteriId = musteriId;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getSoyad() {
        return this.soyad;
    }
    
    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }
    public long getTelno() {
        return this.telno;
    }
    
    public void setTelno(long telno) {
        this.telno = telno;
    }
    public String getCinsiyet() {
        return this.cinsiyet;
    }
    
    public void setCinsiyet(String cinsiyet) {
        this.cinsiyet = cinsiyet;
    }
    public long getTc() {
        return this.tc;
    }
    
    public void setTc(long tc) {
        this.tc = tc;
    }




}


