package Pojo;
// Generated 09.May.2019 23:13:27 by Hibernate Tools 4.3.1



/**
 * Seferler generated by hbm2java
 */
public class Seferler  implements java.io.Serializable {


     private Integer seferId;
     private Musteri musteri;
     private Turlar turlar;

    public Seferler() {
    }

    public Seferler(Musteri musteri, Turlar turlar) {
       this.musteri = musteri;
       this.turlar = turlar;
    }
   
    public Integer getSeferId() {
        return this.seferId;
    }
    
    public void setSeferId(Integer seferId) {
        this.seferId = seferId;
    }
    public Musteri getMusteri() {
        return this.musteri;
    }
    
    public void setMusteri(Musteri musteri) {
        this.musteri = musteri;
    }
    public Turlar getTurlar() {
        return this.turlar;
    }
    
    public void setTurlar(Turlar turlar) {
        this.turlar = turlar;
    }




}


