package Pojo;
// Generated 09.May.2019 23:00:31 by Hibernate Tools 4.3.1



/**
 * Yonetici generated by hbm2java
 */
public class Yonetici  implements java.io.Serializable {


     private Integer YId;
     private String isim;
     private String soyisim;
     private String YAdi;
     private String YSifre;

    public Yonetici() {
    }

    public Yonetici(String isim, String soyisim, String YAdi, String YSifre) {
       this.isim = isim;
       this.soyisim = soyisim;
       this.YAdi = YAdi;
       this.YSifre = YSifre;
    }
   
    public Integer getYId() {
        return this.YId;
    }
    
    public void setYId(Integer YId) {
        this.YId = YId;
    }
    public String getIsim() {
        return this.isim;
    }
    
    public void setIsim(String isim) {
        this.isim = isim;
    }
    public String getSoyisim() {
        return this.soyisim;
    }
    
    public void setSoyisim(String soyisim) {
        this.soyisim = soyisim;
    }
    public String getYAdi() {
        return this.YAdi;
    }
    
    public void setYAdi(String YAdi) {
        this.YAdi = YAdi;
    }
    public String getYSifre() {
        return this.YSifre;
    }
    
    public void setYSifre(String YSifre) {
        this.YSifre = YSifre;
    }




}


